import * as vscode from 'vscode';
import * as path from 'path';
import { ProjectType } from './detector';

/**
 * Project types where Nixpacks' auto-generated build binds to a port other than
 * 8080 (or otherwise misbehaves with Locus's health-check proxy).
 *
 * The biggest offender: static SPAs (Vite, CRA). Nixpacks serves them with a
 * Caddyfile that binds to port 80, but Locus probes 8080. Container → SIGTERM.
 *
 * Types that *do* honour the PORT env var (Next.js, Express, FastAPI, Django,
 * Rails) don't need this fix — Locus injects PORT=8080 and they listen on it.
 */
const PROJECT_TYPES_NEEDING_DOCKERFILE: ReadonlySet<ProjectType> = new Set([
  'react-vite',
]);

export function needsDockerfileFix(projectType: ProjectType): boolean {
  return PROJECT_TYPES_NEEDING_DOCKERFILE.has(projectType);
}

/**
 * Template for each risky project type. Every template must:
 *   - Produce a linux/arm64 image (Locus runs on ARM64)
 *   - EXPOSE 8080
 *   - Start a process that listens on 0.0.0.0:8080
 */
const TEMPLATES: Partial<Record<ProjectType, string>> = {
  // Pure-Node template — avoids base images Locus's ECR mirror may not carry
  // (caddy/nginx are not guaranteed to be mirrored; node is).
  // Uses \`serve -s\` which handles SPA routing (rewrites 404 → index.html).
  'react-vite': `# Auto-generated by ShipShape.
# Builds a Vite/React static site and serves it on port 8080.

FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
EXPOSE 8080
CMD ["serve", "-s", "dist", "-l", "8080"]
`,
};

export function dockerfileTemplate(projectType: ProjectType): string | undefined {
  return TEMPLATES[projectType];
}

// ─── Filesystem I/O ───────────────────────────────────────────────────────────

export function dockerfileUri(workspaceRoot: vscode.Uri): vscode.Uri {
  return vscode.Uri.file(path.join(workspaceRoot.fsPath, 'Dockerfile'));
}

export async function dockerfileExists(workspaceRoot: vscode.Uri): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(dockerfileUri(workspaceRoot));
    return true;
  } catch {
    return false;
  }
}

export async function writeDockerfile(
  workspaceRoot: vscode.Uri,
  content: string
): Promise<vscode.Uri> {
  const uri = dockerfileUri(workspaceRoot);
  await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(content));
  return uri;
}
